import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import type { EvaluationResult } from '../types';

// Register a nice font if needed, but standard fonts are safer for now
// Standard fonts: Helvetica, Times-Roman, Courier

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottomWidth: 2,
    borderBottomColor: '#1e293b',
    paddingBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 5,
  },
  verdictBox: {
    padding: 15,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  verdictText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 5,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  scoreLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#475569',
  },
  scoreValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0ea5e9',
  },
  summaryText: {
    fontSize: 11,
    color: '#334155',
    lineHeight: 1.5,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
  },
  card: {
    width: '48%',
    padding: 12,
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    marginBottom: 15,
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  cardContent: {
    fontSize: 10,
    color: '#475569',
    lineHeight: 1.4,
  },
  bulletPoint: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  bullet: {
    width: 8,
    fontSize: 10,
  },
  bulletText: {
    fontSize: 10,
    color: '#475569',
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 9,
    color: '#94a3b8',
  },
  pitchBox: {
    padding: 12,
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    marginBottom: 20,
    fontStyle: 'italic',
  },
  pitchText: {
    fontSize: 10,
    color: '#64748b',
    lineHeight: 1.4,
  }
});

interface PDFReportProps {
  result: EvaluationResult;
  pitch: string;
}

const PDFReport: React.FC<PDFReportProps> = ({ result, pitch }) => {
  const { summary, details } = result;
  
  const safeArray = (arr: any) => Array.isArray(arr) ? arr : [];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Startup Evaluation Report</Text>
          <Text style={styles.subtitle}>Generated by AI Startup Jury</Text>
        </View>

        {/* Pitch Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>The Pitch</Text>
          <View style={styles.pitchBox}>
            <Text style={styles.pitchText}>"{pitch}"</Text>
          </View>
        </View>

        {/* Final Verdict */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <View style={styles.verdictBox}>
            <View style={styles.scoreRow}>
              <Text style={styles.verdictText}>Verdict: {summary.verdict}</Text>
              <Text style={styles.scoreValue}>{summary.final_score}/10</Text>
            </View>
            <Text style={styles.summaryText}>{details.judge?.one_line_verdict || summary.key_reason}</Text>
          </View>
          
          <View style={{ marginBottom: 15 }}>
            <Text style={[styles.cardTitle, { color: '#ef4444' }]}>Fatal Flaw</Text>
            <Text style={styles.summaryText}>{summary.fatal_flaw || "None identified."}</Text>
          </View>
          
          <View>
            <Text style={[styles.cardTitle, { color: '#0ea5e9' }]}>Recommendation</Text>
            <Text style={styles.summaryText}>{summary.recommendation}</Text>
          </View>
        </View>

        {/* Breakdown Grid */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Agent Analysis</Text>
          <View style={styles.grid}>
            {/* Investor Card */}
            <View style={styles.card}>
              <Text style={styles.cardTitle}>Investor Perspective ({details.investor?.score}/10)</Text>
              <Text style={[styles.cardContent, { marginBottom: 8, fontStyle: 'italic' }]}>
                "{details.investor?.verdict}"
              </Text>
              <Text style={[styles.cardTitle, { fontSize: 8, marginBottom: 4 }]}>Strengths:</Text>
              {safeArray(details.investor?.strengths).slice(0, 3).map((s, i) => (
                <View key={i} style={styles.bulletPoint}>
                  <Text style={styles.bullet}>•</Text>
                  <Text style={styles.bulletText}>{s}</Text>
                </View>
              ))}
            </View>

            {/* Risk Card */}
            <View style={styles.card}>
              <Text style={styles.cardTitle}>Risk Assessment ({details.risk?.score}/10)</Text>
              <Text style={[styles.cardContent, { marginBottom: 8, fontStyle: 'italic' }]}>
                "{details.risk?.verdict}"
              </Text>
              <Text style={[styles.cardTitle, { fontSize: 8, marginBottom: 4 }]}>Key Risks:</Text>
              {safeArray(details.risk?.risks).slice(0, 3).map((r, i) => (
                <View key={i} style={styles.bulletPoint}>
                  <Text style={styles.bullet}>•</Text>
                  <Text style={styles.bulletText}>{r}</Text>
                </View>
              ))}
            </View>

            {/* Customer Card */}
            <View style={styles.card}>
              <Text style={styles.cardTitle}>Customer Insight ({details.customer?.score}/10)</Text>
              <Text style={[styles.cardContent, { marginBottom: 8, fontStyle: 'italic' }]}>
                "{details.customer?.verdict}"
              </Text>
              <Text style={[styles.cardTitle, { fontSize: 8, marginBottom: 4 }]}>Pain Points Solved:</Text>
              {safeArray(details.customer?.pain_points).slice(0, 3).map((p, i) => (
                <View key={i} style={styles.bulletPoint}>
                  <Text style={styles.bullet}>•</Text>
                  <Text style={styles.bulletText}>{p}</Text>
                </View>
              ))}
            </View>

            {/* Debate Insight */}
            <View style={styles.card}>
              <Text style={styles.cardTitle}>Debate Protocol</Text>
              <Text style={[styles.cardContent, { marginBottom: 4 }]}>
                Winner: {details.debate?.winner}
              </Text>
              <Text style={styles.cardContent}>
                "{details.debate?.insight}"
              </Text>
            </View>
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>Confidentially prepared for the Founder.</Text>
          <Text style={styles.footerText}>{new Date().toLocaleDateString()}</Text>
        </View>
      </Page>
    </Document>
  );
};

export default PDFReport;
